### ISSUE TITLE
[BUG] Docker build / release action is broken

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wash-archive#166]
**Describe the bug**
```
#11 318.0 error: failed to run custom build command for `prost-build v0.7.0`
#11 318.0 
#11 318.0 Caused by:
#11 318.0   process didn't exit successfully: `/build/target/release/build/prost-build-96460eb61d9a4b76/build-script-build` (exit status: 101)
#11 318.0   --- stderr
#11 318.0   thread 'main' panicked at 'Failed to find the protoc binary. The PROTOC environment variable is not set, there is no bundled protoc for this platform, and protoc is not in the PATH', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.7.0/build.rs:100:10
#11 318.0   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#11 318.0 warning: build failed, waiting for other jobs to finish...
#11 318.1 error: build failed
#11 ERROR: executor failed running [/bin/sh -c cargo build --release]: exit code: 101
------
 > [builder 8/8] RUN cargo build --release:
#11 316.6    Compiling rand_chacha v0.3.1
#11 318.0 error: failed to run custom build command for `prost-build v0.7.0`
#11 318.0 
#11 318.0 Caused by:
#11 318.0   process didn't exit successfully: `/build/target/release/build/prost-build-96460eb61d9a4b76/build-script-build` (exit status: 101)
#11 318.0   --- stderr
#11 318.0   thread 'main' panicked at 'Failed to find the protoc binary. The PROTOC environment variable is not set, there is no bundled protoc for this platform, and protoc is not in the PATH', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.7.0/build.rs:100:10
#11 318.0   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#11 318.0 warning: build failed, waiting for other jobs to finish...
#11 318.1 error: build failed
------
```

I'm unsure exactly what changed, but there must be a dependency that we're now missing on the ubuntu actions runner. It will be worth evaluating if this can be simply solved by a `cargo update`, or if we need the dependency that depends on `prost-build` as well.

**Environment (please complete the following information) **
GH Actions

**Additional context**
https://github.com/wasmCloud/wash/runs/3566640735?check_suite_focus=true

**Comment by stevelr** [comment]
It's a build problem in the ratsio crate with a prost dependency that seemed to have broken with rust 1.55. I had to fork ratsio to update its dependencies. wasmbus-rpc reexports my fork of ratsio. wasmbus >= 0.3.12 has the fix. There's an open wash pr that updates wasmbus to 0.4.
